### PR TITLE
Add all of the disk info for child elements

### PR DESCRIPTION
**Pull request by DerekParks**
I had a problem similar to issue #7 . I wanted to see the mount points for the children. 

My proposed change returns all child data (not just the name) in the disk_tree's 'child' element.

Feel free to ignore as I am using my fork.  Thanks for the project! 💯

### CODE REVIEW

**Comment by Thermi** [comment]
Works well for me. Please merge it.

**Comment by DerekParks** [comment]
I don't have write access. :)

**Comment by Thermi** [comment]
Yes, I know. It was a general request for @genalt.

**Review by genalt — APPROVED** [review]
Thank you for the patch!

**Pull request merged**
